virt-admin: Fix the error when an invalid URI has been provided
After commit 9d479dd1 fiddled with the cmdConnect's output which used to be a
bit more verbose prior to the mentioned commit, the program flow would result
in a quite confusing error if an invalid URI has been provided:

    error: Failed to connect to the admin server
    Connected to the admin server
    error: <some error>

The problem is that the commit mentioned above relied on the fact that
connect routine always succeeds which is not true.

Signed-off-by: Erik Skultety <eskultet@redhat.com>
(cherry picked from commit 4914494eb8e25ff7938a12fd089c746ec6042bbb)

https://bugzilla.redhat.com/show_bug.cgi?id=1365903
Signed-off-by: Erik Skultety <eskultet@redhat.com>